"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const BlazeDoubleController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/BlazeDoubleController"));
const BlazeCrashController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/BlazeCrashController"));
const SmashDoubleController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/SmashDoubleController"));
const SmashCrashController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/SmashCrashController"));
const SharePadraoController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/SharePadraoController"));
const DashboardController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/DashboardController"));
const MinesController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/MinesController"));
const GluckDoubleController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/GluckDoubleController"));
const GluckCrashController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/GluckCrashController"));
const BetbryDoubleController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/BetbryDoubleController"));
const BetbryCrashController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/BetbryCrashController"));
const BetbryFruitController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/BetbryFruitController"));
const BeetteDoubleController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/BeetteDoubleController"));
const BeetteCrashController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/BeetteCrashController"));
const BeyondDoubleController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/BeyondDoubleController"));
const BeyondCrashController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/BeyondCrashController"));
const NewBotController_1 = __importDefault(global[Symbol.for('ioc.use')]("App/Controllers/Ws/NewBotController"));
let bootMyFriends = new NewBotController_1.default();
bootMyFriends.bootMyFriends();
let BeyondDouble = new BeyondDoubleController_1.default();
BeyondDouble.BeyondDouble();
let BeyondCrash = new BeyondCrashController_1.default();
BeyondCrash.BeyondCrash();
let BeetteDouble = new BeetteDoubleController_1.default();
BeetteDouble.BeetteDouble();
let BeetteCrash = new BeetteCrashController_1.default();
BeetteCrash.BeetteCrash();
let BetbryFruit = new BetbryFruitController_1.default();
BetbryFruit.BetbryFruit();
let BetbryCrash = new BetbryCrashController_1.default();
BetbryCrash.BetbryCrash();
let BetbryDouble = new BetbryDoubleController_1.default();
BetbryDouble.BetbryDouble();
let GluckDouble = new GluckDoubleController_1.default();
GluckDouble.GluckDouble();
let GluckCrash = new GluckCrashController_1.default();
GluckCrash.GluckCrash();
let BlazeCrash = new BlazeCrashController_1.default();
BlazeCrash.BlazeCrash();
let BlazeDouble = new BlazeDoubleController_1.default();
BlazeDouble.BlazeDouble();
let SmashCrash = new SmashCrashController_1.default();
SmashCrash.SmashCrash();
let SmashDouble = new SmashDoubleController_1.default();
SmashDouble.SmashDouble();
let SharePadrao = new SharePadraoController_1.default();
SharePadrao.SharePadrao();
let newBots = new MinesController_1.default();
newBots.NewBots();
let suporteBot = new MinesController_1.default();
suporteBot.suporteBot();
let mines = new MinesController_1.default();
mines.Mines();
let dashboard = new DashboardController_1.default();
dashboard.Dashboard();
//# sourceMappingURL=socket.js.map